name: Deploy to EB

on:
  push:
    branches:
      - master

jobs:
  buildAndTest:
    name: CI Pipeline
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: ['16.x']

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

  deploy:
    name: CD Pipeline
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: ['16.x']

    needs: buildAndTest
    steps:
      # - uses: actions/checkout@v2
      - name: Create env file
        run: |
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
          cat .env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        # run: |
        #   touch .env
        #   echo SERVER_PORT=8081 >> .env
        #   echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
        #   echo DB_HOST=${{ secrets.DB_HOST }} >> .env
        #   echo DB_USER=${{ secrets.DB_USER }} >> .env
        #   echo DB_PSWD=${{ secrets.DB_PSWD }} >> .env
        #   echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        #   echo PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} >> .env
        #   echo AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} >> .env
        #   echo AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} >> .env
        #   echo BUCKET=${{ secrets.BUCKET }} >> .env
        #   cat .env

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Install AWS CLI 2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          which aws
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEPLOY_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' './aws/*' './node_modules/*' './dist/*' awscliv2.zip

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.DEPLOY_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.DEPLOY_SECRET_KEY }}
          application_name: ${{ secrets.DEPLOY_APP_NAME }}
          environment_name: ${{ secrets.DEPLOY_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.SHA }}
          deployment_package: deploy.zip
